"""create all tables with computed spread

Revision ID: 1a0b13ec9066
Revises: 60d1d0d2c9c5
Create Date: 2026-06-11 21:05:08.244524

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 (used via pgvector.sqlalchemy.vector.VECTOR)
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a0b13ec9066'
down_revision: Union[str, None] = '60d1d0d2c9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_status', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('buy_box', sa.Text(), nullable=False),
    sa.Column('buy_box_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('buyer_tier', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('deals_viewed', sa.Integer(), nullable=True),
    sa.Column('deals_offered_on', sa.Integer(), nullable=True),
    sa.Column('offers_accepted', sa.Integer(), nullable=True),
    sa.Column('offers_rejected', sa.Integer(), nullable=True),
    sa.Column('deals_closed', sa.Integer(), nullable=True),
    sa.Column('deads_fell_through', sa.Integer(), nullable=True),
    sa.Column('avg_spread_closed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_lifetime_spread', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('last_pitch_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jv_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('deals_linked', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('total_deals_submitted', sa.Integer(), nullable=True),
    sa.Column('total_deals_closed', sa.Integer(), nullable=True),
    sa.Column('total_revenue_generated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_buyer_feedback_score', sa.Float(), nullable=True),
    sa.Column('title_issue_rate', sa.Float(), nullable=True),
    sa.Column('overprice_flag_count', sa.Integer(), nullable=True),
    sa.Column('total_split_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('occupancy_status', sa.Text(), nullable=True),
    sa.Column('repair_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lot_size', sa.Text(), nullable=True),
    sa.Column('zoning', sa.Text(), nullable=True),
    sa.Column('utilities_available', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('topography_access', sa.Text(), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=False),
    sa.Column('deal_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('arv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('floor_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contract_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('title_status', sa.Text(), nullable=False),
    sa.Column('photos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('assigned_buyer_id', sa.UUID(), nullable=True),
    sa.Column('jv_partner_id', sa.UUID(), nullable=True),
    sa.Column('jv_split_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_spread', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('jv_payout', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('my_payout', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('spread', sa.Numeric(precision=12, scale=2), sa.Computed('asking_price - contract_price', ), nullable=True),
    sa.ForeignKeyConstraint(['assigned_buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['jv_partner_id'], ['jv_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('touch_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reply_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_body', sa.Text(), nullable=True),
    sa.Column('reply_intent', sa.Text(), nullable=True),
    sa.Column('ai_extracted_insights', sa.Text(), nullable=True),
    sa.Column('buyer_profile_updated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    op.drop_table('email_verifications')
    op.drop_table('deals')
    op.drop_table('jv_partners')
    op.drop_table('buyers')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
