"""add scheduled_send_at to campaigns

Revision ID: fac01b5a3b28
Revises: 1a0b13ec9066
Create Date: 2026-06-12 16:32:44.931681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac01b5a3b28'
down_revision: Union[str, None] = '1a0b13ec9066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('scheduled_send_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'scheduled_send_at')
    # ### end Alembic commands ###
